services:
  vc-issuer:
    #build: ./
    image: semtech/mu-javascript-template:1.9.0
    restart: no
    labels:
      - logging=true
    environment:
      TZ: Europe/Brussels
      NODE_ENV: development
      ISSUER_URL: https://192.168.1.118/ // needs to be accessible from https://192.168.1.118/.well-known/openid-credential-issuer, use the dispatcher. It can contain a path as well, then it would be https://192.168.1.118/.well-known/openid-credential-issuer/your/path/here
    ports:
      - '8081:80'
      - '9228:9229'
    volumes:
      - ../app-decide/config/vc-issuer:/config
      - ./:/app
    networks:
      - debug

networks:
  debug:
    external: true
